### ISSUE TITLE
How i can use more 16 symbols

### ISSUE THREAD

**Issue by Sitmobedaf** [Alvin-LB/NameTagChanger#8]
http://img11.lostpic.net/2018/11/12/dbb94210d1b593110e594d273785376b.jpg
How i can use Scoreboard teams via this library?

**Comment by Alvin-LB** [comment]
In theory, there should be nothing special you'd need to do. Just use the regular Scoreboard API and the player to a team where you have set the prefix and/or suffix.

This library does some trickery to make this work with the name changes, but as far as I know it should work as normal.
